server: 
  port: 8762

spring:
  profiles: test
  application:
    name: eureka-client

eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/

logging:
  path: ./eureka-client
  file: ./eureka-client.log