spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev
  application:
    name: service-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8769
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
logging:
  path: ./service-zuul
  file: ./service-zuul.log
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eam
    api-b:
      path: /api-b/**
      serviceId: eureka-client
  sensitive-headers: Origin
#  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin

---
spring:
  profiles: test
  application:
    name: service-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8769
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
logging:
  path: ./service-zuul
  file: ./service-zuul.log
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eam
    api-b:
      path: /api-b/**
      serviceId: eureka-client
#  sensitive-headers: Origin
#  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin
