spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev
  application:
    name: service-zuul
server:
  port: 8769
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
logging:
  path: ./service-zuul
  file: ./service-zuul.log
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eam
    api-b:
      path: /api-b/**
      serviceId: eureka-client
  sensitive-headers: Origin
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin

---
spring:
  profiles: test
  application:
    name: service-zuul
server:
  port: 8769
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
logging:
  path: ./service-zuul
  file: ./service-zuul.log
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eam
    api-b:
      path: /api-b/**
      serviceId: eureka-client
#  sensitive-headers: Origin
#  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin
